server:
  host: 0.0.0.0
  port: 5101
  debug: false
file_endpoints:
- id: victron
  description: Victron system monitor log files
  base_dir: data
  allow_patterns:
  - log_*.csv
  - daily/solar_daily.csv
  - state.json
  - state_mapping.yaml
  - system_configuration.yaml
command_endpoints: []
